export const MENULIST_DATA_START = "MENULIST_DATA_START";
export const MENULIST_DATA_SUCCESS = "MENULIST_DATA_SUCCESS";
export const MENULIST_DATA_FAILURE = "MENULIST_DATA_FAILURE";

export const FOODLIST_DATA_START = "FOODLIST_DATA_START";
export const FOODLIST_DATA_SUCCESS = "FOODLIST_DATA_SUCCESS";
export const FOODLIST_DATA_FAILURE = "FOODLIST_DATA_FAILURE";